create table member
(
    id       bigint generated by default as identity,
    age      integer not null,
    username varchar(255),
    team_id  bigint,
    primary key (id)
);

create table member2
(
    id       bigint generated by default as identity,
    age      integer not null,
    username varchar(255),
    team_id  bigint,
    primary key (id)
);

create table team
(
    team_id bigint generated by default as identity,
    name    varchar(255),
    test1   integer not null,
    test2   integer not null,
    test3   integer not null,
    primary key (team_id)
);

insert into team(name, test1, test2, test3) values ('test', 10, 20, 30);